sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: my_take_away
    username: root
    password: QWe3230938
  redis:
    host: localhost
    port: 6379
    password: 3230938