my:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: my_take_away
    username: root
    password: QWe3230938
  redis:
    host: localhost
    port: 6379
    password: 3230938
  alioss:
    endpoint: xxx
    access-key-secret: xxx
    access-key-id: xxxx
    bucket-name: xxx
  wechat:
    appid: wx85897a1f3f8c953a
    secret: 7c44bd43e02017519ccaabdabade387d